// SEO metadata for every tool — drives individual page rankings
export const TOOL_SEO = {
  merge: {
    title: 'Merge PDF Files Online Free — Combine PDFs in Seconds | PDF Studio',
    description: 'Merge multiple PDF files into one online for free. No watermark, no signup. Drag to reorder, then combine. Works on any device.',
    h1: 'Merge PDF Files Online',
    intro: 'Combine multiple PDF documents into a single file instantly. Upload your PDFs, arrange them in the order you want, and download your merged PDF — free, with no watermark.',
    keywords: 'merge pdf, combine pdf, join pdf files, merge pdf free, combine pdf online',
    faqs: [
      { q: 'How many PDFs can I merge at once?', a: 'You can merge up to 20 PDF files in a single operation. There is no page limit on the combined output.' },
      { q: 'Will merging add a watermark?', a: 'No. PDF Studio never adds watermarks to your documents — merged or otherwise.' },
      { q: 'Can I reorder pages before merging?', a: 'Yes. Use the order field to specify which file goes first. For example, entering "2,1,3" puts the second uploaded file first.' },
      { q: 'What file size limit is there for merging?', a: 'There is no enforced file size limit. Very large PDFs (100MB+) may take a few extra seconds to process.' },
      { q: 'Are my files kept private?', a: 'Yes. All uploaded files are stored temporarily and automatically deleted within 2 hours. We never read or share your content.' },
      { q: 'Does PDF Studio work on mobile phones?', a: 'Yes. PDF Studio works entirely in the browser — no app download required. It works on iOS, Android, Windows, and Mac.' },
    ],
  },
  split: {
    title: 'Split PDF Online Free — Separate PDF Pages | PDF Studio',
    description: 'Split a PDF into multiple files online. Extract individual pages or define custom page ranges. Free, instant, no signup required.',
    h1: 'Split PDF Online Free',
    intro: 'Separate a PDF document into multiple files. Split every page into individual PDFs, or define custom ranges like 1-3, 4-6. Download all parts as a ZIP file.',
    keywords: 'split pdf, separate pdf pages, divide pdf, extract pages from pdf, split pdf free',
    faqs: [
      { q: 'Can I split a PDF into individual pages?', a: 'Yes. Choose "Each page as separate file" and every page becomes its own PDF, bundled together in a ZIP download.' },
      { q: 'How do I split a PDF by page range?', a: 'Select "Custom ranges" and enter ranges like 1-5, 6-10. Each range becomes a separate PDF file in the output ZIP.' },
      { q: 'Will the original PDF be modified?', a: 'No. Your original file is never altered. We create new PDF files from the pages you specify.' },
      { q: 'Is there a page limit when splitting?', a: 'No. You can split PDFs with hundreds of pages. The tool handles large documents without any page restrictions.' },
      { q: 'Can I split and then merge again?', a: 'Yes. You can split a PDF first, download specific parts, then use the Merge PDF tool to recombine them in any order.' },
    ],
  },
  compress: {
    title: 'Compress PDF Online Free — Reduce PDF File Size | PDF Studio',
    description: 'Compress PDF files and reduce file size online for free. Choose low, medium, or high compression. No quality loss on text. Instant download.',
    h1: 'Compress PDF — Reduce File Size Online',
    intro: 'Reduce PDF file size without compromising quality. Our compressor uses MuPDF for fast structure optimization and Ghostscript for maximum image compression — giving you the smallest possible file.',
    keywords: 'compress pdf, reduce pdf size, pdf compressor, compress pdf free, shrink pdf',
    faqs: [
      { q: 'How much can I reduce a PDF file size?', a: 'Most image-heavy PDFs reduce by 40–70%. Text-only or already-optimized PDFs see less reduction. We always guarantee the output is never larger than your original.' },
      { q: 'What is the difference between compression levels?', a: 'Low removes redundant data without re-encoding images. Medium balances quality and size. High uses Ghostscript and MuPDF together and picks the best result.' },
      { q: 'Does compression affect text quality?', a: 'No. Text in PDFs is vector-based and is never degraded by compression. Only embedded images are re-encoded at lower quality.' },
      { q: 'Why does it say "Already optimized"?', a: 'Some PDFs — especially those already exported from design tools — are fully optimized. Our tool detected that any further compression would increase the file size, so we returned your original.' },
      { q: 'How fast is the compression?', a: 'Low and Medium levels complete in 1–3 seconds using MuPDF direct structure manipulation. High level runs MuPDF and Ghostscript in parallel and takes 5–15 seconds depending on file size.' },
      { q: 'Is there a file size limit for compression?', a: 'No hard limit. Very large files (200MB+) may take 30–60 seconds on High level due to full page re-rendering.' },
    ],
  },
  'pdf-to-word': {
    title: 'PDF to Word Converter Free Online — Convert PDF to DOCX | PDF Studio',
    description: 'Convert PDF to Word document online free. Get an editable DOC or DOCX file from any PDF. Formatting preserved. No signup, instant download.',
    h1: 'PDF to Word Converter — Free Online',
    intro: 'Convert any PDF to an editable Word document. Our PDF to Word converter uses LibreOffice to preserve fonts, layout, tables, and formatting as accurately as possible.',
    keywords: 'pdf to word, convert pdf to word, pdf to docx, pdf to doc free, pdf converter',
    faqs: [
      { q: 'Is the converted Word document editable?', a: 'Yes. The output is a standard .docx file you can edit in Microsoft Word, Google Docs, or LibreOffice Writer.' },
      { q: 'Does it preserve formatting?', a: 'We preserve formatting as accurately as possible using LibreOffice. Complex layouts with multiple columns or custom fonts may need minor adjustments.' },
      { q: 'Can I convert a scanned PDF to Word?', a: 'Scanned PDFs contain images of text, not real text. Use our OCR tool first to extract text, then copy it into a Word document.' },
      { q: 'What if the PDF is password protected?', a: 'Remove the password first using the Unlock PDF tool, then convert to Word.' },
      { q: 'Is there a page limit for PDF to Word conversion?', a: 'No page limit. Large documents may take longer to process but are fully supported.' },
    ],
  },
  'word-to-pdf': {
    title: 'Word to PDF Converter Free Online — DOC to PDF | PDF Studio',
    description: 'Convert Word documents to PDF online free. Upload DOC or DOCX and get a perfect PDF instantly. No watermark, no signup.',
    h1: 'Word to PDF — Free Online Converter',
    intro: 'Convert Microsoft Word documents to PDF format instantly. Upload your DOC or DOCX file and download a professionally formatted PDF that looks identical on any device.',
    keywords: 'word to pdf, convert word to pdf, doc to pdf, docx to pdf, word to pdf free',
    faqs: [
      { q: 'Does converting Word to PDF change the formatting?', a: 'No. Converting to PDF locks your formatting exactly as it appears in Word, ensuring it looks the same on any device or printer.' },
      { q: 'What Word formats are supported?', a: 'We support .doc (Word 97–2003) and .docx (Word 2007 and later). Both are converted using LibreOffice.' },
      { q: 'Can I convert Word with tracked changes to PDF?', a: 'Yes. Accept or reject your tracked changes in Word before converting to control what appears in the final PDF.' },
      { q: 'Are embedded images preserved in the PDF?', a: 'Yes. All images, charts, and diagrams embedded in your Word document are included in the PDF output.' },
      { q: 'Is the resulting PDF searchable?', a: 'Yes. Text in your Word document is preserved as real, searchable text in the PDF — not converted to images.' },
    ],
  },
  'pdf-to-jpg': {
    title: 'PDF to JPG Converter Free Online — Convert PDF Pages to Images | PDF Studio',
    description: 'Convert PDF pages to JPG images online free. Extract every page as a high-quality JPG. Choose 72, 150, or 300 DPI. Instant ZIP download.',
    h1: 'PDF to JPG — Convert PDF Pages to Images',
    intro: 'Convert each page of your PDF into a JPG image. Choose your preferred resolution — 72 DPI for web use, 150 DPI for standard quality, or 300 DPI for print-quality images.',
    keywords: 'pdf to jpg, convert pdf to image, pdf to jpeg, extract images from pdf, pdf to jpg free',
    faqs: [
      { q: 'What DPI should I choose?', a: '72 DPI for web display or email previews, 150 DPI for standard quality presentations, 300 DPI if you need print-quality images.' },
      { q: 'How do I get multiple pages?', a: 'All pages are converted and bundled into a single ZIP file for easy download. You can extract individual JPGs from the ZIP.' },
      { q: 'Can I convert just one page of the PDF?', a: 'Currently all pages are converted. Use the Extract Pages tool first to isolate specific pages, then convert to JPG.' },
      { q: 'What is the maximum number of pages converted?', a: 'Up to 20 pages are converted per operation. For longer PDFs, split them first and convert each part separately.' },
      { q: 'Does the JPG quality match the original PDF?', a: 'At 300 DPI, the output images are very high quality. The appearance depends on the original PDF resolution and content type.' },
    ],
  },
  'jpg-to-pdf': {
    title: 'JPG to PDF Converter Free Online — Images to PDF | PDF Studio',
    description: 'Convert JPG images to PDF online free. Combine multiple photos into one PDF. Set orientation and margins. No watermark, instant download.',
    h1: 'JPG to PDF — Convert Images to PDF Online',
    intro: 'Convert one or multiple JPG, PNG, or WebP images into a single PDF. Set orientation to portrait, landscape, or auto-match your image size. Each image becomes one page.',
    keywords: 'jpg to pdf, image to pdf, png to pdf, photos to pdf, convert jpg to pdf free',
    faqs: [
      { q: 'Can I combine multiple images into one PDF?', a: 'Yes. Upload multiple images and they will each become a page in your PDF, in the order you upload them.' },
      { q: 'What image formats are supported?', a: 'JPG, JPEG, PNG, and WebP images are all supported. Mixed formats can be combined into a single PDF.' },
      { q: 'How do I control page orientation?', a: 'Choose Auto to match each image\'s own orientation, Portrait to force vertical layout, or Landscape for horizontal layout.' },
      { q: 'Can I add margins around my images?', a: 'Yes. Set the margin field in pixels. A margin of 20–40px creates a clean white border around each image.' },
      { q: 'Is image quality preserved in the PDF?', a: 'Images are encoded at 90% JPEG quality inside the PDF, which preserves excellent detail while keeping file size reasonable.' },
    ],
  },
  unlock: {
    title: 'Unlock PDF Online Free — Remove PDF Password | PDF Studio',
    description: 'Remove password protection from PDF files online free. Unlock encrypted PDFs instantly. Enter your password and download an unlocked version.',
    h1: 'Unlock PDF — Remove Password Protection',
    intro: 'Remove password protection from PDF files you own. Enter the PDF password, and we\'ll generate an unlocked version you can open without a password on any device.',
    keywords: 'unlock pdf, remove pdf password, pdf password remover, unlock protected pdf, decrypt pdf',
    faqs: [
      { q: 'Can I unlock a PDF without the password?', a: 'No. You must know the correct password to unlock a PDF. This tool is for removing restrictions from files you legitimately own.' },
      { q: 'What happens to the original file?', a: 'Your original password-protected file is kept unchanged. We create a new unlocked copy for you to download.' },
      { q: 'Does unlocking remove editing restrictions too?', a: 'This tool removes the open password (required to view the file). Edit, print, and copy restrictions require the owner password, which must also be provided.' },
      { q: 'Will the unlocked PDF work on all devices?', a: 'Yes. The unlocked PDF is a standard PDF with no password, compatible with all PDF viewers.' },
      { q: 'Is unlocking my own PDF legal?', a: 'Unlocking PDFs you own is legal in most jurisdictions. Do not use this tool to bypass security on files you don\'t own.' },
    ],
  },
  watermark: {
    title: 'Add Watermark to PDF Online Free | PDF Studio',
    description: 'Add text watermarks to PDF files online free. Customize font, size, color, opacity, rotation and position. No signup, instant download.',
    h1: 'Add Watermark to PDF — Free Online Tool',
    intro: 'Stamp a text watermark on every page of your PDF. Customize the text, color, opacity, rotation angle, and position — center, corner, or anywhere on the page.',
    keywords: 'add watermark to pdf, pdf watermark, watermark pdf free, stamp pdf, confidential watermark',
    faqs: [
      { q: 'Can I add a transparent watermark?', a: 'Yes. Set the opacity slider to any value between 5% and 100%. Lower values create a subtle, semi-transparent watermark.' },
      { q: 'Can I change the watermark text?', a: 'Yes. Enter any text — CONFIDENTIAL, DRAFT, your company name, or any custom text up to any length.' },
      { q: 'Can I rotate the watermark?', a: 'Yes. Set rotation in degrees. -45 creates the classic diagonal watermark look. 0 places text horizontally.' },
      { q: 'Is the watermark added to every page?', a: 'Yes. The watermark is applied to all pages in the document. Selective page watermarking is not currently available.' },
      { q: 'Can I change the watermark color?', a: 'Yes. Use the color picker to set any color. Black at low opacity (20–30%) is most common for professional documents.' },
    ],
  },
  ocr: {
    title: 'OCR PDF Online Free — Make Scanned PDF Searchable | PDF Studio',
    description: 'Convert scanned PDF to searchable text online free using OCR. Extract text from image-based PDFs. Supports English, Hindi, and more.',
    h1: 'OCR PDF — Convert Scanned Documents to Searchable Text',
    intro: 'Use Optical Character Recognition to extract text from scanned PDFs and image-based documents. Get selectable, searchable text from any scan in seconds.',
    keywords: 'ocr pdf, pdf ocr, scanned pdf to text, make pdf searchable, optical character recognition pdf',
    faqs: [
      { q: 'What languages does OCR support?', a: 'English, Hindi, French, German, and Spanish. Select your document\'s language before processing for the best accuracy.' },
      { q: 'How accurate is the OCR?', a: 'Accuracy depends on scan quality. Clear, high-resolution scans typically achieve 95%+ accuracy. Handwritten text is not supported.' },
      { q: 'How many pages does OCR process?', a: 'Up to 10 pages are processed per operation. For longer documents, split them first and run OCR on each section.' },
      { q: 'Can I copy the extracted text?', a: 'Yes. The extracted text is displayed in full on screen and can be selected, copied, and pasted into any application.' },
      { q: 'What makes a good scan for OCR?', a: 'Scan at 300 DPI or higher, use black and white mode if possible, ensure the document is flat and well-lit, and avoid skewed pages.' },
    ],
  },

  // ── 13 newly added tools ────────────────────────────────────────────────────
  rotate: {
    title: 'Rotate PDF Pages Online Free — Fix Sideways PDFs | PDF Studio',
    description: 'Rotate PDF pages online free. Fix upside-down or sideways pages. Rotate all pages or specific ones by 90°, 180°, or 270°. No signup.',
    h1: 'Rotate PDF Pages — Fix Orientation Online',
    intro: 'Fix sideways or upside-down PDF pages instantly. Rotate all pages or only selected ones by 90°, 180°, or 270°. The corrected PDF is ready to download in seconds.',
    keywords: 'rotate pdf, rotate pdf pages, flip pdf, pdf orientation, rotate pdf online free',
    faqs: [
      { q: 'Can I rotate only specific pages?', a: 'Yes. Enter the page numbers in the "Pages" field — for example "1,3,5" or "2-6" — and only those pages will be rotated.' },
      { q: 'How do I rotate all pages at once?', a: 'Leave the Pages field blank. When empty, the rotation is applied to every page in the document.' },
      { q: 'Can I rotate a PDF 180 degrees?', a: 'Yes. Select "180°" from the Rotation dropdown to flip all pages upside down.' },
      { q: 'Does rotating the PDF affect text quality?', a: 'No. Rotation is a metadata change to the PDF — no re-rendering occurs, so text and images remain at full quality.' },
      { q: 'Can I undo a rotation?', a: 'Yes. Run the rotate tool again and apply the opposite rotation. For example, to undo a 90° clockwise rotation, apply a 270° rotation.' },
    ],
  },

  protect: {
    title: 'Protect PDF with Password Online Free — Encrypt PDF | PDF Studio',
    description: 'Add password protection to PDF files online for free. Encrypt with AES-256. Set open and owner passwords. No software needed.',
    h1: 'Protect PDF — Add Password Encryption Online',
    intro: 'Secure your PDF documents with strong AES-256 password encryption. Set a password to prevent unauthorized access. No software installation needed — works directly in your browser.',
    keywords: 'protect pdf, password protect pdf, encrypt pdf, add password to pdf, secure pdf online',
    faqs: [
      { q: 'What encryption standard is used?', a: 'We use AES-256 encryption via QPDF, the same standard used by banks and governments. It is currently unbreakable by brute force.' },
      { q: 'What is the difference between user and owner passwords?', a: 'The user password is required to open and view the PDF. The owner password controls editing, printing, and copying permissions. If you only set one, both use the same password.' },
      { q: 'Can I protect a PDF that is already password protected?', a: 'Yes. Unlock it first using the Unlock PDF tool, then protect it again with your new password.' },
      { q: 'Will the protected PDF work on all PDF readers?', a: 'Yes. AES-256 encrypted PDFs are supported by Adobe Acrobat, Preview (macOS), and all major PDF readers.' },
      { q: 'Can I remove the password later?', a: 'Yes. Use the Unlock PDF tool — enter the password you set, and we will generate an unlocked version.' },
      { q: 'Does PDF Studio store my password?', a: 'No. Passwords are processed in memory only and are never logged or stored. Your files are deleted within 2 hours.' },
    ],
  },

  crop: {
    title: 'Crop PDF Pages Online Free — Trim PDF Margins | PDF Studio',
    description: 'Crop PDF pages online for free. Remove unwanted margins, trim whitespace, or define a custom crop area. No signup, instant download.',
    h1: 'Crop PDF — Trim Pages Online Free',
    intro: 'Remove unwanted margins or whitespace from PDF pages. Define a custom crop box using X offset, Y offset, width, and height in PDF points. All pages are cropped uniformly.',
    keywords: 'crop pdf, trim pdf margins, crop pdf pages, remove margins pdf, crop pdf online free',
    faqs: [
      { q: 'What units are used for cropping?', a: 'Crop dimensions are in PDF points (pt). 1 point = 1/72 inch. A standard A4 page is 595 × 842 pt. A US Letter page is 612 × 792 pt.' },
      { q: 'How do I remove margins from a PDF?', a: 'Start with an X of 36 and Y of 36 (0.5-inch margins), then set width to 523 and height to 770 for A4, or 540 × 720 for Letter.' },
      { q: 'Does cropping delete content?', a: 'Cropping sets a visible area (CropBox) but the underlying content still exists. For true content removal, use a PDF editor.' },
      { q: 'Is the crop applied to every page?', a: 'Yes. The same crop dimensions are applied uniformly to all pages.' },
      { q: 'Can I crop scanned PDFs?', a: 'Yes. Cropping works on any PDF including scanned documents, image PDFs, and text PDFs.' },
    ],
  },

  'page-numbers': {
    title: 'Add Page Numbers to PDF Online Free | PDF Studio',
    description: 'Add page numbers to PDF files online for free. Choose position, starting number, prefix, and font size. Works on any PDF. No signup.',
    h1: 'Add Page Numbers to PDF — Free Online Tool',
    intro: 'Automatically number every page of your PDF. Choose the position — bottom center, top right, or other corners — set a starting number, add a prefix like "Page ", and customize the font size.',
    keywords: 'add page numbers to pdf, pdf page numbers, number pdf pages, pdf page numbering, add numbers to pdf free',
    faqs: [
      { q: 'Can I start page numbering from a number other than 1?', a: 'Yes. Set the "Start numbering at" field to any number. For example, enter 3 to start numbering from 3.' },
      { q: 'Can I add a prefix like "Page" before the number?', a: 'Yes. Enter a prefix such as "Page " (with trailing space) in the Prefix field to get "Page 1", "Page 2", etc.' },
      { q: 'Where are the page numbers placed?', a: 'Choose from bottom center, bottom left, bottom right, or top center. Bottom center is the most common standard placement.' },
      { q: 'Can I skip the first page (for a cover)?', a: 'Not currently. Page numbers are added to all pages. As a workaround, remove page 1, add numbers, then merge with the original cover page.' },
      { q: 'What font is used for page numbers?', a: 'Page numbers use Helvetica, a clean sans-serif font. Font size is configurable — 10-12pt is standard for most documents.' },
    ],
  },

  'ppt-to-pdf': {
    title: 'PowerPoint to PDF Converter Free Online — PPT to PDF | PDF Studio',
    description: 'Convert PowerPoint presentations to PDF online for free. Upload PPT or PPTX and get a perfect PDF instantly. No watermark, no signup.',
    h1: 'PowerPoint to PDF — Free Online Converter',
    intro: 'Convert PowerPoint presentations to PDF format in seconds. Upload your PPT or PPTX file and get a perfectly formatted PDF that preserves all your slides, animations text, and images.',
    keywords: 'ppt to pdf, powerpoint to pdf, convert ppt to pdf, pptx to pdf, powerpoint to pdf free',
    faqs: [
      { q: 'What PowerPoint formats are supported?', a: 'Both .ppt (PowerPoint 97–2003) and .pptx (PowerPoint 2007 and later) are fully supported.' },
      { q: 'Are slide animations preserved in the PDF?', a: 'No. PDF is a static format. Animations are not preserved, but each slide\'s final state is shown as a full PDF page.' },
      { q: 'Does conversion preserve fonts and images?', a: 'Yes. Fonts and images are embedded in the output PDF. If a custom font is missing, it falls back to the closest system font.' },
      { q: 'How many slides can I convert?', a: 'No slide limit. Large presentations with many slides may take a few extra seconds to process.' },
      { q: 'Is the output PDF presentation-ready?', a: 'Yes. Each slide becomes a full-page PDF in landscape orientation, ready for printing or sharing.' },
    ],
  },

  'excel-to-pdf': {
    title: 'Excel to PDF Converter Free Online — XLS to PDF | PDF Studio',
    description: 'Convert Excel spreadsheets to PDF online for free. Upload XLS or XLSX files and get a formatted PDF instantly. No signup, no watermark.',
    h1: 'Excel to PDF — Free Online Converter',
    intro: 'Convert Excel spreadsheets to PDF format instantly. Upload your XLS or XLSX file and download a neatly formatted PDF that preserves your data, tables, and column layouts.',
    keywords: 'excel to pdf, convert excel to pdf, xls to pdf, xlsx to pdf, spreadsheet to pdf free',
    faqs: [
      { q: 'What Excel formats are supported?', a: 'Both .xls (Excel 97–2003) and .xlsx (Excel 2007 and later) are supported.' },
      { q: 'Are formulas preserved in the PDF?', a: 'No. PDF is a static format and shows the calculated values of formulas, not the formulas themselves.' },
      { q: 'Will all columns fit on the PDF page?', a: 'LibreOffice tries to fit content to the page. Very wide spreadsheets may span multiple pages. Adjust column widths in Excel before converting for best results.' },
      { q: 'Are multiple sheets included?', a: 'All visible sheets in the workbook are included in the PDF, each starting on a new page.' },
      { q: 'Are charts and graphs preserved?', a: 'Yes. Charts and embedded graphs are converted to images and included in the PDF output.' },
    ],
  },

}
