// All tools definition — single source of truth
export const TOOLS = [
  // ── Organize ─────────────────────────────────────────────────────────────
  {
    id: 'merge',
    name: 'Merge PDF',
    desc: 'Combine multiple PDFs in any order.',
    category: 'organize',
    icon: '⊕',
    color: 'orange',
    endpoint: '/organize/merge',
    method: 'POST',
    multiFile: true,
    accepts: '.pdf',
    fields: [],
  },
  {
    id: 'split',
    name: 'Split PDF',
    desc: 'Separate into multiple files by page range.',
    category: 'organize',
    icon: '⊘',
    color: 'orange',
    endpoint: '/organize/split',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'mode', type: 'select', label: 'Split mode', options: [
        { value: 'each', label: 'Each page as separate file' },
        { value: 'ranges', label: 'Custom ranges' },
      ]},
      { name: 'ranges', type: 'text', label: 'Ranges (e.g. 1-3,4-6)', dependsOn: { mode: 'ranges' } },
    ],
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    desc: 'Rotate pages by 90°, 180°, or 270°.',
    category: 'organize',
    icon: '↻',
    color: 'orange',
    endpoint: '/organize/rotate',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'angle', type: 'select', label: 'Rotation', options: [
        { value: '90', label: '90° clockwise' },
        { value: '180', label: '180°' },
        { value: '270', label: '90° counter-clockwise' },
      ]},
      { name: 'pages', type: 'text', label: 'Pages (leave blank for all)', placeholder: 'e.g. 1,3,5' },
    ],
  },

  // ── Optimize ─────────────────────────────────────────────────────────────
  {
    id: 'compress',
    name: 'Compress PDF',
    desc: 'Reduce file size without losing quality.',
    category: 'optimize',
    icon: '⊜',
    color: 'green',
    endpoint: '/optimize/compress',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'level', type: 'select', label: 'Compression level', options: [
        { value: 'low',    label: 'Low — fast, preserves image quality' },
        { value: 'medium', label: 'Medium — 40–60% smaller, good quality' },
        { value: 'high',   label: 'High — 60–80% smaller, max compression' },
      ]},
    ],
  },
  {
    id: 'ocr',
    name: 'OCR PDF',
    desc: 'Make scanned PDFs searchable and selectable.',
    category: 'optimize',
    icon: 'T',
    color: 'green',
    endpoint: '/optimize/ocr',
    method: 'POST',
    accepts: '.pdf',
    returnsText: true,
    fields: [
      { name: 'lang', type: 'select', label: 'Document language', options: [
        { value: 'eng', label: 'English' },
        { value: 'hin', label: 'Hindi' },
        { value: 'fra', label: 'French' },
        { value: 'deu', label: 'German' },
        { value: 'spa', label: 'Spanish' },
      ]},
    ],
  },

  // ── Convert to PDF ────────────────────────────────────────────────────────
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    desc: 'Convert images to PDF with layout control.',
    category: 'convert',
    icon: '🖼',
    color: 'blue',
    endpoint: '/convert/jpg-to-pdf',
    method: 'POST',
    multiFile: true,
    accepts: '.jpg,.jpeg,.png,.webp',
    fields: [
      { name: 'orientation', type: 'select', label: 'Orientation', options: [
        { value: 'auto', label: 'Auto (match image)' },
        { value: 'portrait', label: 'Portrait' },
        { value: 'landscape', label: 'Landscape' },
      ]},
      { name: 'margin', type: 'number', label: 'Margin (px)', placeholder: '0' },
    ],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    desc: 'Convert DOC / DOCX to shareable PDF.',
    category: 'convert',
    icon: 'W',
    color: 'blue',
    endpoint: '/convert/office-to-pdf',
    method: 'POST',
    accepts: '.doc,.docx',
    fields: [],
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    desc: 'Convert PPT / PPTX slides to PDF.',
    category: 'convert',
    icon: 'P',
    color: 'blue',
    endpoint: '/convert/office-to-pdf',
    method: 'POST',
    accepts: '.ppt,.pptx',
    fields: [],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    desc: 'Convert XLS / XLSX spreadsheets to PDF.',
    category: 'convert',
    icon: 'X',
    color: 'blue',
    endpoint: '/convert/office-to-pdf',
    method: 'POST',
    accepts: '.xls,.xlsx',
    fields: [],
  },

  // ── Convert from PDF ──────────────────────────────────────────────────────
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    desc: 'Convert PDF pages to JPG images.',
    category: 'convert',
    icon: '🖼',
    color: 'purple',
    endpoint: '/convert/pdf-to-jpg',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'dpi', type: 'select', label: 'Quality (DPI)', options: [
        { value: '72', label: '72 DPI (web)' },
        { value: '150', label: '150 DPI (standard)' },
        { value: '300', label: '300 DPI (print)' },
      ]},
    ],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    desc: 'Get an editable DOC from any PDF.',
    category: 'convert',
    icon: 'W',
    color: 'purple',
    endpoint: '/convert/pdf-to-office',
    method: 'POST',
    accepts: '.pdf',
    fields: [{ name: 'format', type: 'hidden', value: 'docx' }],
  },

  // ── Edit ──────────────────────────────────────────────────────────────────
  {
    id: 'watermark',
    name: 'Add Watermark',
    desc: 'Stamp text watermarks with custom style.',
    category: 'edit',
    icon: '◈',
    color: 'accent',
    endpoint: '/edit/watermark',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'text', type: 'text', label: 'Watermark text', placeholder: 'CONFIDENTIAL', required: true },
      { name: 'color', type: 'color', label: 'Color', defaultValue: '#000000' },
      { name: 'opacity', type: 'range', label: 'Opacity', min: 0.05, max: 1, step: 0.05, defaultValue: 0.3 },
      { name: 'fontSize', type: 'number', label: 'Font size', placeholder: '48' },
      { name: 'rotation', type: 'number', label: 'Rotation (degrees)', placeholder: '-45' },
      { name: 'position', type: 'select', label: 'Position', options: [
        { value: 'center', label: 'Center' },
        { value: 'top-left', label: 'Top left' },
        { value: 'top-right', label: 'Top right' },
        { value: 'bottom-left', label: 'Bottom left' },
        { value: 'bottom-right', label: 'Bottom right' },
      ]},
    ],
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    desc: 'Add numbered headers or footers.',
    category: 'edit',
    icon: '#',
    color: 'accent',
    endpoint: '/edit/page-numbers',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'position', type: 'select', label: 'Position', options: [
        { value: 'bottom-center', label: 'Bottom center' },
        { value: 'bottom-left', label: 'Bottom left' },
        { value: 'bottom-right', label: 'Bottom right' },
        { value: 'top-center', label: 'Top center' },
      ]},
      { name: 'startAt', type: 'number', label: 'Start numbering at', placeholder: '1' },
      { name: 'prefix', type: 'text', label: 'Prefix (optional)', placeholder: 'Page ' },
      { name: 'fontSize', type: 'number', label: 'Font size', placeholder: '12' },
    ],
  },
  {
    id: 'crop',
    name: 'Crop PDF',
    desc: 'Trim margins or define a crop area.',
    category: 'edit',
    icon: '⊡',
    color: 'accent',
    endpoint: '/edit/crop',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'x', type: 'number', label: 'X offset (pts)', placeholder: '0' },
      { name: 'y', type: 'number', label: 'Y offset (pts)', placeholder: '0' },
      { name: 'width', type: 'number', label: 'Width (pts)', placeholder: '595', required: true },
      { name: 'height', type: 'number', label: 'Height (pts)', placeholder: '842', required: true },
    ],
  },

  // ── Security ──────────────────────────────────────────────────────────────
  {
    id: 'unlock',
    name: 'Unlock PDF',
    desc: 'Remove password protection from your PDFs.',
    category: 'security',
    icon: '🔓',
    color: 'red',
    endpoint: '/security/unlock',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'password', type: 'password', label: 'PDF password', placeholder: 'Enter password', required: true },
    ],
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    desc: 'Encrypt PDFs with a strong password.',
    category: 'security',
    icon: '🔒',
    color: 'red',
    endpoint: '/security/protect',
    method: 'POST',
    accepts: '.pdf',
    fields: [
      { name: 'userPassword', type: 'password', label: 'Password', placeholder: 'Enter password', required: true },
    ],
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All tools' },
  { id: 'organize', label: 'Organize' },
  { id: 'optimize', label: 'Optimize' },
  { id: 'convert', label: 'Convert' },
  { id: 'edit', label: 'Edit' },
  { id: 'security', label: 'Security' },
];

export const COLOR_MAP = {
  red:    { bg: 'rgba(255,107,107,0.12)', text: '#ff6b6b' },
  blue:   { bg: 'rgba(107,181,255,0.12)', text: '#6bb5ff' },
  green:  { bg: 'rgba(107,255,184,0.12)', text: '#6bffb8' },
  orange: { bg: 'rgba(255,184,107,0.12)', text: '#ffb86b' },
  purple: { bg: 'rgba(184,107,255,0.12)', text: '#b86bff' },
  accent: { bg: 'rgba(232,213,176,0.12)', text: '#e8d5b0' },
};
